# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/IP downloads and resources/Nexys-4-DDR-Master.xdc

# XDC: imports/new/eth_ref_clk.xdc

# Block Designs: bd/MB_PL/MB_PL.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL || ORIG_REF_NAME==MB_PL} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_DP_SLICE_0/MB_PL_DP_SLICE_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_DP_SLICE_0 || ORIG_REF_NAME==MB_PL_DP_SLICE_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_SEG_SLICE_0/MB_PL_SEG_SLICE_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_SEG_SLICE_0 || ORIG_REF_NAME==MB_PL_SEG_SLICE_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_SEG_SLICE1_0/MB_PL_SEG_SLICE1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_SEG_SLICE1_0 || ORIG_REF_NAME==MB_PL_SEG_SLICE1_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_SEG_SLICE2_0/MB_PL_SEG_SLICE2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_SEG_SLICE2_0 || ORIG_REF_NAME==MB_PL_SEG_SLICE2_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_SEG_SLICE3_0/MB_PL_SEG_SLICE3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_SEG_SLICE3_0 || ORIG_REF_NAME==MB_PL_SEG_SLICE3_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_SEG_SLICE4_0/MB_PL_SEG_SLICE4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_SEG_SLICE4_0 || ORIG_REF_NAME==MB_PL_SEG_SLICE4_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_SEG_SLICE5_0/MB_PL_SEG_SLICE5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_SEG_SLICE5_0 || ORIG_REF_NAME==MB_PL_SEG_SLICE5_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_SEG_SLICE6_0/MB_PL_SEG_SLICE6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_SEG_SLICE6_0 || ORIG_REF_NAME==MB_PL_SEG_SLICE6_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_SEG_SLICE7_0/MB_PL_SEG_SLICE7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_SEG_SLICE7_0 || ORIG_REF_NAME==MB_PL_SEG_SLICE7_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_SSegDriver_0_0/MB_PL_SSegDriver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_SSegDriver_0_0 || ORIG_REF_NAME==MB_PL_SSegDriver_0_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_axi_ethernetlite_0_0/MB_PL_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_axi_ethernetlite_0_0 || ORIG_REF_NAME==MB_PL_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_axi_gpio_0_0/MB_PL_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_axi_gpio_0_0 || ORIG_REF_NAME==MB_PL_axi_gpio_0_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_axi_smc_0/MB_PL_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_axi_smc_0 || ORIG_REF_NAME==MB_PL_axi_smc_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_axi_timer_0_0/MB_PL_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_axi_timer_0_0 || ORIG_REF_NAME==MB_PL_axi_timer_0_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_axi_uartlite_0_0/MB_PL_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_axi_uartlite_0_0 || ORIG_REF_NAME==MB_PL_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_clk_wiz_1_0/MB_PL_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_clk_wiz_1_0 || ORIG_REF_NAME==MB_PL_clk_wiz_1_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_mdm_1_0/MB_PL_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_mdm_1_0 || ORIG_REF_NAME==MB_PL_mdm_1_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_microblaze_0_0/MB_PL_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_microblaze_0_0 || ORIG_REF_NAME==MB_PL_microblaze_0_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_microblaze_0_axi_intc_0/MB_PL_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_microblaze_0_axi_intc_0 || ORIG_REF_NAME==MB_PL_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_microblaze_0_axi_periph_0/MB_PL_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MB_PL_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_microblaze_0_xlconcat_0/MB_PL_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_microblaze_0_xlconcat_0 || ORIG_REF_NAME==MB_PL_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_mii_to_rmii_0_0/MB_PL_mii_to_rmii_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_mii_to_rmii_0_0 || ORIG_REF_NAME==MB_PL_mii_to_rmii_0_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_rst_clk_wiz_1_100M_0/MB_PL_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MB_PL_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_rst_mig_7series_0_81M_0/MB_PL_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==MB_PL_rst_mig_7series_0_81M_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_xlconstant_1_0/MB_PL_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_xlconstant_1_0 || ORIG_REF_NAME==MB_PL_xlconstant_1_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_mig_7series_0_0/MB_PL_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_mig_7series_0_0 || ORIG_REF_NAME==MB_PL_mig_7series_0_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_dlmb_v10_0/MB_PL_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_dlmb_v10_0 || ORIG_REF_NAME==MB_PL_dlmb_v10_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_ilmb_v10_0/MB_PL_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_ilmb_v10_0 || ORIG_REF_NAME==MB_PL_ilmb_v10_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_dlmb_bram_if_cntlr_0/MB_PL_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MB_PL_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_ilmb_bram_if_cntlr_0/MB_PL_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MB_PL_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_lmb_bram_0/MB_PL_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_lmb_bram_0 || ORIG_REF_NAME==MB_PL_lmb_bram_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_xbar_0/MB_PL_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_xbar_0 || ORIG_REF_NAME==MB_PL_xbar_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_PmodHYGRO_0_1/MB_PL_PmodHYGRO_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_PmodHYGRO_0_1 || ORIG_REF_NAME==MB_PL_PmodHYGRO_0_1} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_PmodALS_0_0/MB_PL_PmodALS_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_PmodALS_0_0 || ORIG_REF_NAME==MB_PL_PmodALS_0_0} -quiet] -quiet

# IP: bd/MB_PL/ip/MB_PL_PmodWIFI_0_0/MB_PL_PmodWIFI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_PL_PmodWIFI_0_0 || ORIG_REF_NAME==MB_PL_PmodWIFI_0_0} -quiet] -quiet

# XDC: bd/MB_PL/MB_PL_ooc.xdc
