# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Emann/Desktop/MBTST/Plant/Plant.cache/wt [current_project]
set_property parent.project_path C:/Users/Emann/Desktop/MBTST/Plant/Plant.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_repo_paths {
  {c:/Users/Emann/Desktop/MBTST/Plant/7Seg IP}
  c:/Users/Emann/Desktop/MBTST/Plant/PMODS
} [current_project]
set_property ip_output_repo c:/Users/Emann/Desktop/MBTST/Plant/Plant.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/hdl/MB_PL_wrapper.vhd
add_files C:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/MB_PL.bd
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_ethernetlite_0_0/MB_PL_axi_ethernetlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_ethernetlite_0_0/MB_PL_axi_ethernetlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_ethernetlite_0_0/MB_PL_axi_ethernetlite_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_ethernetlite_0_0/MB_PL_axi_ethernetlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_gpio_0_0/MB_PL_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_gpio_0_0/MB_PL_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_gpio_0_0/MB_PL_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_12/bd_2c04_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_21/bd_2c04_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_24/bd_2c04_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_25/bd_2c04_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_26/bd_2c04_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_27/bd_2c04_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_28/bd_2c04_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_29/bd_2c04_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_22/bd_2c04_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_23/bd_2c04_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_13/bd_2c04_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_14/bd_2c04_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_15/bd_2c04_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_16/bd_2c04_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_17/bd_2c04_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_4/bd_2c04_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_5/bd_2c04_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_6/bd_2c04_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_7/bd_2c04_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_8/bd_2c04_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_1/bd_2c04_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_1/bd_2c04_psr0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_2/bd_2c04_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_2/bd_2c04_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_3/bd_2c04_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/bd_0/ip/ip_3/bd_2c04_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_timer_0_0/MB_PL_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_timer_0_0/MB_PL_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_uartlite_0_0/MB_PL_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_uartlite_0_0/MB_PL_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_axi_uartlite_0_0/MB_PL_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_clk_wiz_1_0/MB_PL_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_clk_wiz_1_0/MB_PL_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_clk_wiz_1_0/MB_PL_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_mdm_1_0/MB_PL_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_mdm_1_0/MB_PL_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_microblaze_0_0/MB_PL_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_microblaze_0_0/MB_PL_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_microblaze_0_0/MB_PL_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_microblaze_0_axi_intc_0/MB_PL_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_microblaze_0_axi_intc_0/MB_PL_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_microblaze_0_axi_intc_0/MB_PL_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_mii_to_rmii_0_0/MB_PL_mii_to_rmii_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_mii_to_rmii_0_0/MB_PL_mii_to_rmii_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_rst_clk_wiz_1_100M_0/MB_PL_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_rst_clk_wiz_1_100M_0/MB_PL_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_rst_clk_wiz_1_100M_0/MB_PL_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_rst_mig_7series_0_81M_0/MB_PL_rst_mig_7series_0_81M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_rst_mig_7series_0_81M_0/MB_PL_rst_mig_7series_0_81M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_rst_mig_7series_0_81M_0/MB_PL_rst_mig_7series_0_81M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_mig_7series_0_0/MB_PL_mig_7series_0_0/user_design/constraints/MB_PL_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_mig_7series_0_0/MB_PL_mig_7series_0_0/user_design/constraints/MB_PL_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_dlmb_v10_0/MB_PL_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_dlmb_v10_0/MB_PL_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_ilmb_v10_0/MB_PL_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_ilmb_v10_0/MB_PL_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_dlmb_bram_if_cntlr_0/MB_PL_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_ilmb_bram_if_cntlr_0/MB_PL_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_lmb_bram_0/MB_PL_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_xbar_0/MB_PL_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodHYGRO_0_1/src/PmodHYGRO_axi_iic_0_0/PmodHYGRO_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodHYGRO_0_1/src/PmodHYGRO_axi_iic_0_0/PmodHYGRO_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodHYGRO_0_1/MB_PL_PmodHYGRO_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodHYGRO_0_1/src/PmodHYGRO_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodHYGRO_0_1/src/PmodHYGRO_axi_timer_0_0/PmodHYGRO_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodHYGRO_0_1/src/PmodHYGRO_axi_timer_0_0/PmodHYGRO_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodHYGRO_0_1/src/PmodHYGRO_pmod_bridge_0_0/PmodHYGRO_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodHYGRO_0_1/src/PmodHYGRO_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodALS_0_0/src/PmodALS_pmod_bridge_0_0/PmodALS_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodALS_0_0/src/PmodALS_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodALS_0_0/MB_PL_PmodALS_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodALS_0_0/src/PmodALS_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodALS_0_0/src/PmodALS_axi_quad_spi_0_0/PmodALS_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodALS_0_0/src/PmodALS_axi_quad_spi_0_0/PmodALS_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodALS_0_0/src/PmodALS_axi_quad_spi_0_0/PmodALS_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodALS_0_0/src/PmodALS_axi_quad_spi_0_0/PmodALS_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodWIFI_0_0/src/PmodWIFI_pmod_bridge_0_0/PmodWIFI_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodWIFI_0_0/src/PmodWIFI_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodWIFI_0_0/MB_PL_PmodWIFI_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodWIFI_0_0/src/PmodWIFI_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodWIFI_0_0/src/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/ip/MB_PL_PmodWIFI_0_0/src/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/sources_1/bd/MB_PL/MB_PL_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/constrs_1/imports/IP downloads and resources/Nexys-4-DDR-Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/constrs_1/imports/IP downloads and resources/Nexys-4-DDR-Master.xdc}}]

read_xdc C:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/constrs_1/imports/new/eth_ref_clk.xdc
set_property used_in_implementation false [get_files C:/Users/Emann/Desktop/MBTST/Plant/Plant.srcs/constrs_1/imports/new/eth_ref_clk.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top MB_PL_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MB_PL_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MB_PL_wrapper_utilization_synth.rpt -pb MB_PL_wrapper_utilization_synth.pb"
