
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = freertos901_xilinx
 PARAMETER OS_VER = 1.1
 PARAMETER PROC_INSTANCE = MB_UC
 PARAMETER SYSINTC_SPEC = *
 PARAMETER SYSTMR_DEV = *
 PARAMETER SYSTMR_SPEC = true
 PARAMETER stdin = uart
 PARAMETER stdout = uart
 PARAMETER use_idle_hook = true
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu
 PARAMETER DRIVER_VER = 2.6
 PARAMETER HW_INSTANCE = MB_UC
 PARAMETER extra_compiler_flags = -ffunction-sections -fdata-sections -Wall -Wextra -O0 -g3
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = PmodALS
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = ALS
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = PmodHYGRO
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = HYGRO
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = PmodWIFI
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = WIFI
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = emaclite
 PARAMETER DRIVER_VER = 4.3
 PARAMETER HW_INSTANCE = ether
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.3
 PARAMETER HW_INSTANCE = gpio0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = intc
 PARAMETER DRIVER_VER = 3.7
 PARAMETER HW_INSTANCE = ints
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.2
 PARAMETER HW_INSTANCE = mb_mem_dlmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.2
 PARAMETER HW_INSTANCE = mb_mem_ilmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = mig_7series
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = mig_7
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = tmrctr
 PARAMETER DRIVER_VER = 4.4
 PARAMETER HW_INSTANCE = timer0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 3.2
 PARAMETER HW_INSTANCE = uart
END


